### ISSUE TITLE
Unexpected Cut (Ctrl-X) behavior in code-folding branch

### ISSUE THREAD

**Issue by secondgeargames** [engor/Ted2Go#122] opened 2018-03-27 22:21 UTC
For some reason I am getting this:
![observed](https://user-images.githubusercontent.com/1726597/37998067-2db239d0-31eb-11e8-9984-5e951f516392.gif)
instead of this:
![expected](https://user-images.githubusercontent.com/1726597/37998076-34dd8160-31eb-11e8-844f-ec1a44ca2dfc.gif)

The code is from  mojo/graphics/font.monkey2 The keystrokes are: Shift-Down-Down to select, Crtl-X to cut.

**Comment by engor** [comment] 2018-03-31 04:25
Hm, I can't reproduce in latest dev version.
Please, try the latest and tell me is it OK or not.

**Comment by secondgeargames** [comment] 2018-03-31 14:45
The problem is in the code-folding branch. I was trying to enjoy some code folding functionality before official release, so I built Ted2Go from code-folding branch using your Monkey2 fork.

**Comment by engor** [comment] 2018-03-31 15:01
Ok. I almost fix that...

**Comment by engor** [comment] 2018-04-01 14:29
Should be fixed now in **dev**.

**Closed by engor** 2018-04-01 14:29 UTC
